[tool.poetry]
name = "hexlet-code"
version = "0.1.0"
description = "Task Manager"
authors = ["DzmitrySha <ravenbydev@gmail.com>"]
#packages = []

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.1.2"
python-dotenv = "^0.21.0"

[tool.poetry.dev-dependencies]
flake8 = "^5.0.4"
gunicorn = "^20.1.0"
pytest-cov = "^4.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

#[tool.poetry.scripts]
#task-manager = "task_manager.manage.py:main"
