# Generated by Django 4.1.1 on 2022-11-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_alter_taskstatus_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskStatus',
        ),
    ]
