# Generated by Django 4.1.1 on 2022-11-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_label_delete_labels'),
        ('tasks', '0005_alter_tasks_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='label',
            field=models.ManyToManyField(blank=True, related_name='labels', to='labels.label', verbose_name='Label'),
        ),
    ]
