# Generated by Django 4.1.1 on 2022-11-07 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_tasks_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='label',
            new_name='labels',
        ),
    ]
