# Generated by Django 4.1.1 on 2022-11-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_rename_label_tasks_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='labels',
        ),
    ]
